apiVersion: v1
kind: Secret
metadata:
  name: secret-name
type: Opaque
data:
  username: YWRtaW4=
  password: bXlzZWNyZXRwYXNz
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret-name
            key: username
            optional: false
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-name
            key: password
            optional: false
  restartPolicy: Never