all:
  hosts:
    db:
      ansible_host: 192.168.56.10
      ansible_ssh_private_key_file: 'private_key'
    backend:
      ansible_host: 192.168.56.11
      ansible_ssh_private_key_file: 'private_key'
    frontend:
      ansible_host: 192.168.56.12
      ansible_ssh_private_key_file: 'private_key'

  children:
    web_servers:
      hosts:
        frontend:
        backend:
    db_servers:
      hosts:
        db:
    servers_group:
      children:
        web_servers:
        db_servers:
      vars:
        ansible_user: host
